// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvelF_LIWuWEF6wyOQpOH8sbp3IB-NAtk',
    appId: '1:485934712868:web:03508d381972272f3770b1',
    messagingSenderId: '485934712868',
    projectId: 'iprep-app-fa99d',
    authDomain: 'iprep-app-fa99d.firebaseapp.com',
    storageBucket: 'iprep-app-fa99d.appspot.com',
    measurementId: 'G-T1JDZ0SLK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV06MAVc01bBSRp1XEwe8Z1iyL2p_5se4',
    appId: '1:485934712868:android:6c2d0af0507b9b4f3770b1',
    messagingSenderId: '485934712868',
    projectId: 'iprep-app-fa99d',
    storageBucket: 'iprep-app-fa99d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDInfsyb-fC3z0ZLBotA_73J6B3o2jhksw',
    appId: '1:485934712868:ios:bdb684c1bc00ef3d3770b1',
    messagingSenderId: '485934712868',
    projectId: 'iprep-app-fa99d',
    storageBucket: 'iprep-app-fa99d.appspot.com',
    androidClientId: '485934712868-5bo5rom1lplrpvs5eiu3nad32lu78oo4.apps.googleusercontent.com',
    iosClientId: '485934712868-o59pcut397qt9rre9c4ppidosbn2d2vs.apps.googleusercontent.com',
    iosBundleId: 'org.idreameducation.iprepapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDInfsyb-fC3z0ZLBotA_73J6B3o2jhksw',
    appId: '1:485934712868:ios:bdb684c1bc00ef3d3770b1',
    messagingSenderId: '485934712868',
    projectId: 'iprep-app-fa99d',
    storageBucket: 'iprep-app-fa99d.appspot.com',
    androidClientId: '485934712868-5bo5rom1lplrpvs5eiu3nad32lu78oo4.apps.googleusercontent.com',
    iosClientId: '485934712868-o59pcut397qt9rre9c4ppidosbn2d2vs.apps.googleusercontent.com',
    iosBundleId: 'org.idreameducation.iprepapp',
  );
}
